services:
  db:
    image: postgres
    container_name: db
    env_file:
      - backend/.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: django_backend
    environment:
      DB_HOST: db
    env_file:
      - backend/.env
    ports:
      - 8000:8000
    depends_on:
      - db

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - backend

volumes:
  postgres_data:
