services:
  db:
    image: postgres
    container_name: db
    env_file:
      - backend/.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: django_backend
    environment:
      DB_HOST: db
    volumes:
      - static_volume:/app/staticfiles
    env_file:
      - backend/.env
    expose:
      - 8000
    depends_on:
      - db

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    environment:
      NODE_ENV: production
    volumes:
      - frontend_build:/app/build
    depends_on:
      - backend
  
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - static_volume:/app/staticfiles
      - frontend_build:/usr/share/nginx/html
    ports:
      - 8000:80
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  static_volume:
  frontend_build: